app:
  topic: ${TOPIC:test_topic}
  queue: ${QUEUE:test_queue}
server:
  port: 8082
spring:
  application:
    name: publisher
  activemq:
    broker-url: ${ACTIVE_MQ_URL:tcp://localhost:61616}
    packages:
      trusted: org.springframework.remoting.support,java.lang,com.epam