app:
  topic: ${TOPIC:test_topic}
  queue: ${QUEUE:test_queue}
  virtual-topic: ${VIRTUAL_TOPIC:VirtualTopic.virtual_topic}
server:
  port: 8084
spring:
  application:
    name: virtual-consumers
  activemq:
    broker-url: ${ACTIVE_MQ_URL:tcp://localhost:61616}
    packages:
      trusted: org.springframework.remoting.support,java.lang,com.epam